name: Build Toolbox

on:
  push:
    tags:
      - 'toolbox-v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: ./.github/actions/build-tauri
        with:
          app-name: toolbox
          jackserver-url: ${{ secrets.JACKIT_JACKSERVER_URL }}
          jackserver-token: ${{ secrets.JACKIT_JACKSERVER_TOKEN }}
