name: Build Toolbox

on:
  push:
    tags:
      - 'toolbox-v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: ./.github/actions/build-tauri
        with:
          app-name: toolbox
          rustserver-url: ${{ secrets.JACKIT_RUSTSERVER_URL }}
          rustserver-token: ${{ secrets.JACKIT_RUSTSERVER_TOKEN }}
